name: cd workflow
on:
  push:
    branches:
      - "main"

jobs:
  cd-workflow-job:
    name: cd workflow
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
